"""DiminirTamanhoCampoNomeEmail

Revision ID: 737814dbf3b4
Revises: 9770d2238d9c
Create Date: 2024-06-20 10:50:28.639550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '737814dbf3b4'
down_revision = '9770d2238d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
